### PR TITLE
add plane to CM_BRUSHES

### PR DESCRIPTION
**Pull request by BobTheBob9**

### CODE REVIEW

**Comment by BobTheBob9** [comment]
thought: there's actually a chance that the flags lump could also be indexing into planes, that'd give us 2 indexes into planes and 1 into side planes

**Comment by BobTheBob9** [comment]
would make sense with the numbers i've seen in it

**Review by snake-biscuits — COMMENTED** [review]
To change from `short unknown_1[2];` to `short unknown_1, plane;` you need to remove `"unknown_1": 2` from `_arrays`, since this is where lists are created

**Review by snake-biscuits — COMMENTED** [review]
definitely could be flags of some kind
so far I was assuming contents flags would come from an index into `CM_UNIQUE_CONTENTS`

to check flags w/ bsp_tool you can do this;
```python
>>> import bsp_tool
>>> r1 = bsp_tool.branches.respawn.titanfall
>>> # has defines for Contents, TraceGroup & TraceMask flags / enums
>>> bsp = bsp_tool.load_bsp(".../mp_whatever.bsp")
>>> # NOTE: bsp.branch will also give you the branch_script
>>> r1.Contents(0)  # 0
<Contents.EMPTY: 0>
>>> r1.Contents(1027)
<Contents.UNUSED|WINDOW|SOLID: 1027>
```

[`respawn.titanfall`](https://github.com/snake-biscuits/bsp_tool/blob/master/bsp_tool/branches/respawn/titanfall.py#L221-L318) defines flags for TextureData / MaterialSort (`Flags`, includes vertex types) & the Trace / Collision masks etc. mentioned earlier

[`valve.source`](https://github.com/snake-biscuits/bsp_tool/blob/master/bsp_tool/branches/valve/source.py#L185-L316) defines some flags for other structs, including the `Surface` flags, which are limited to a range of 16 bits & seem to be mixed in with `titanfall.Flags`

I am planning to add these flag definitions to some structs so when you print to console you can see the flags immediately, just have to figure out a system for that

**Pull request merged**
